#!/usr/bin/env bash
# Deploys free5GC onto the kind cluster created by 02-create-kind-cluster.sh.
#
# free5GC's default chart values assume network interfaces / IP ranges from
# the maintainers' own lab. On kind, every node only has a single eth0, and
# the N6 (Data Network / internet-facing) interface must live on the real
# docker bridge subnet so it can actually route packets out. This script
# detects that subnet automatically and generates a values override file.
set -euo pipefail

# Belt-and-braces: make kubectl/kind/helm resolve even if the calling
# shell's PATH doesn't have ~/.local/bin on it (e.g. a non-interactive
# shell, or one that never sourced .bashrc).

# Resolve the real (non-root) user's home even when invoked via sudo --
# sudo resets $HOME to /root, which would otherwise point PATH/KUBECONFIG
# at /root/.local/bin and /root/.kube/config instead of where
# kubectl/kind/helm and the kind cluster's kubeconfig actually live.
REAL_HOME="$HOME"
if [ -n "${SUDO_USER:-}" ]; then
  REAL_HOME="$(getent passwd "$SUDO_USER" | cut -d: -f6)"
fi
export PATH="$REAL_HOME/.local/bin:$PATH"
export KUBECONFIG="${KUBECONFIG:-$REAL_HOME/.kube/config}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_DIR="$(dirname "$SCRIPT_DIR")"
CHART_DIR="$LAB_DIR/charts/towards5gs-helm/charts/free5gc"
NAMESPACE="core"
RELEASE="core"

# Dedicated node network created by 02-create-kind-cluster.sh.
DOCKER_NET="${KIND_EXPERIMENTAL_DOCKER_NETWORK:-corelab-net}"

echo "== Detecting the kind nodes' docker network subnet ($DOCKER_NET) =="
DOCKER_NET_JSON=$(docker network inspect "$DOCKER_NET" --format '{{json .IPAM.Config}}')
echo "  $DOCKER_NET IPAM: $DOCKER_NET_JSON"

read -r N6_SUBNET N6_CIDR N6_GATEWAY N6_UPF_IP <<EOF
$(python3 - "$DOCKER_NET_JSON" <<'PY'
import ipaddress, json, sys
configs = json.loads(sys.argv[1])
# Prefer the IPv4 config
cfg = next(c for c in configs if ":" not in c["Subnet"])
net = ipaddress.ip_network(cfg["Subnet"])
gw = cfg.get("Gateway") or str(list(net.hosts())[0])
# .200 sits outside docker's --ip-range (.0/25), so it can never collide
# with an address docker hands to a kind node.
upf_ip = str(net.network_address + 200)
print(str(net.network_address), net.prefixlen, gw, upf_ip)
PY
)
EOF

echo "  N6 subnet:  $N6_SUBNET/$N6_CIDR"
echo "  N6 gateway: $N6_GATEWAY"
echo "  UPF N6 IP:  $N6_UPF_IP"

OVERRIDE_FILE="$LAB_DIR/cluster/free5gc-values-kind.generated.yaml"
cat > "$OVERRIDE_FILE" <<YAML
# Auto-generated by scripts/03-deploy-free5gc.sh -- do not hand-edit,
# re-run the script to regenerate after cluster recreation.
global:
  n6network:
    enabled: true
    name: n6network
    type: ipvlan
    masterIf: eth0
    subnetIP: ${N6_SUBNET}
    cidr: ${N6_CIDR}
    gatewayIP: ${N6_GATEWAY}
    excludeIP: ${N6_GATEWAY}

free5gc-upf:
  upf:
    n6if:
      ipAddress: ${N6_UPF_IP}
    # towards5gs's bundled UPF image (towards5gs/free5gc-upf:latest, free5GC
    # v3.2.1-era) hardcodes a check that only accepts gtp5g 0.8.1 <= v < 0.9.0.
    # That gtp5g line does not compile against this host's kernel without
    # non-trivial patching (removed NETIF_F_LLTX flag, reworked
    # rtnl_link_ops.newlink signature). gtp5g v0.10.2 (current) DOES compile
    # cleanly here, so instead we point the UPF at the current official
    # free5GC image, which targets that modern gtp5g range. The UPF config
    # schema (version 1.0.3: pfcp/gtpu/dnnList) is unchanged between v3.2.1
    # and v4.2.3, so this is a drop-in swap.
    image:
      name: free5gc/upf
      tag: v4.2.3

# The SMF is the UPF's direct N4/PFCP peer. Pairing an old (v3.2.1-era) SMF
# with the new (v4.2.3) UPF broke PDU session establishment (SMF rejected the
# UPF's PFCP Session Establishment Response: "received unexpected SEID
# response message ... SEID:0, expected: <n>" -- a PFCP library difference
# between the two release lines). Bumping the SMF to the same v4.2.3 line
# fixes it. Its config schema (info.version 1.0.7) was already what this
# chart generates, so only the image + binary/cert paths needed changing
# (see smf-deployment.yaml / smf-configmap.yaml).
free5gc-smf:
  smf:
    image:
      name: free5gc/smf
      tag: v4.2.3

# SMF (v4.2.3) calls UDM's Nudm_SDM GetSessionManagementSubscriptionData when
# establishing a PDU session, and can't parse the response from the old
# (v3.2.1-era) UDM: "Get SessionManagementSubscriptionData error: undefined
# response type" -> SMF rejects the session (gsm cause 50). Bumping UDM (and
# its data-layer peer UDR, which has the same old/new image split risk) to
# the same v4.2.3 line fixes it. Config schemas matched already (UDM
# info.version 1.0.3 unchanged; UDR content is a superset-compatible match
# for the official 1.1.0 schema) -- only image + binary/cert paths needed
# changing (see udm-deployment.yaml / udr-deployment.yaml + their configmaps).
free5gc-udm:
  udm:
    image:
      name: free5gc/udm
      tag: v4.2.3

free5gc-udr:
  udr:
    image:
      name: free5gc/udr
      tag: v4.2.3

# Upgrading UDM/UDR surfaced further old-vs-new data-model breaks with the
# still-old AMF/AUSF/NSSF/PCF/NRF/WebUI (subscriber auth schema, then a 404
# on UDM's NSSAI endpoint and missing mandatory IEs on UECM registration) --
# the whole stack needs to be on the same v4.2.3 line to interoperate
# cleanly. Same pattern throughout: image swap + absolute binary/cert paths
# (see each NF's deployment.yaml/configmap.yaml); AMF also needed
# strategy:Recreate (static N2 ipvlan IP, same as SMF/UPF) and WebUI's
# config schema needed nrfUri/webServer added (info.version bumped
# 1.0.1 -> 1.0.3).
free5gc-amf:
  amf:
    image:
      name: free5gc/amf
      tag: v4.2.3

free5gc-ausf:
  ausf:
    image:
      name: free5gc/ausf
      tag: v4.2.3

free5gc-nssf:
  nssf:
    image:
      name: free5gc/nssf
      tag: v4.2.3

free5gc-pcf:
  pcf:
    image:
      name: free5gc/pcf
      tag: v4.2.3

free5gc-nrf:
  nrf:
    image:
      name: free5gc/nrf
      tag: v4.2.3

# Bitnami removed versioned free-tier tags from docker.io/bitnami/mongodb in
# 2025; older pinned versions are mirrored under bitnamilegacy instead.
# WebUI is only reachable through a loopback port-forward
# (scripts/09-open-grafana.sh), never a NodePort on the node network.
free5gc-webui:
  webui:
    image:
      name: free5gc/webui
      tag: v4.2.3
    service:
      type: ClusterIP

mongodb:
  image:
    repository: bitnamilegacy/mongodb
    tag: "4.4.4"
YAML

echo "== Generated override: $OVERRIDE_FILE =="
cat "$OVERRIDE_FILE"

echo "== Creating namespace =="
kubectl create ns "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

echo "== Installing free5GC (release: $RELEASE) =="
helm -n "$NAMESPACE" upgrade --install "$RELEASE" "$CHART_DIR" \
  -f "$OVERRIDE_FILE" \
  --timeout 10m --wait

echo "== Pods =="
kubectl -n "$NAMESPACE" get pods -o wide

echo "== Services =="
kubectl -n "$NAMESPACE" get svc

echo
echo "free5GC WebUI is ClusterIP-only (not exposed on any host/node port)."
echo "Reach it on this machine only with:  ./scripts/09-open-grafana.sh"
echo "  -> http://127.0.0.1:5000   (default login: admin / free5gc)"
